#!/system/bin/sh

UKM=/data/UKM;
BB=$UKM/busybox;
#DEVICE=`sh $UKM/device/.device.sh`;

UCI_CONFIG=$UKM/config.json;
UCI_ACTION=$UKM/actions/;
UCI_DEVICE=$UKM/device/;
UCI_FILES=$UKM/files/;
#DEBUG=$UKM/debug;
#SYNAPSE_SD_DIR=/sdcard/Synapse;

export UKM BB UCI_ACTION UCI_DEVICE
ts0=`date +"%s"`
function timeit() {
	ts=`date +"%s"`
	_ts=$1
	echo $1 $((ts-ts0))
}
if [ ! -f $UCI_CONFIG ]; then
	echo "{sections: [" > $UCI_CONFIG
	#$UKM/cpufreq.sh >> $UCI_CONFIG
	#echo "," >> $UCI_CONFIG
	$UKM/liveopp.sh >> $UCI_CONFIG
	timeit liveopp
	echo "," >> $UCI_CONFIG
	$UKM/mali.sh >> $UCI_CONFIG
	timeit mali
	echo "," >> $UCI_CONFIG
	$UKM/mali_vape.sh >> $UCI_CONFIG
	timeit mali_vape
	echo "," >> $UCI_CONFIG
	$UKM/u8500_power.sh >> $UCI_CONFIG
	timeit power
	echo "," >> $UCI_CONFIG
	$UKM/config.json.generate.mem >> $UCI_CONFIG
	timeit mem
	$UKM/config.json.generate.io >> $UCI_CONFIG
	timeit io
	echo "]}" >> $UCI_CONFIG
fi

case "${1}" in
  config)
		$BB cat $UCI_CONFIG;;
  configpath)
		$BB echo $UCI_CONFIG;;
  actionpath)
		$BB echo $UCI_ACTION;;
	reset)
		$BB rm -f $UCI_CONFIG;;
esac;
